#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Interactive installer for the server-monitor-rs panel.
#
# Produces (in ./server-monitor-rs/ by default):
#   - docker-compose.yml   (copied from deploy/docker/)
#   - .env                 (with generated secrets)
#   - Caddyfile            (only if the user opted into Caddy)
#
# Then runs `docker compose up -d` and prints next-step guidance.
# -----------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." &>/dev/null && pwd)"
COMPOSE_SRC="$REPO_ROOT/deploy/docker/docker-compose.yml"
CADDY_TEMPLATE="$REPO_ROOT/deploy/docker/Caddyfile.tmpl"

GREEN=$'\033[0;32m'
YELLOW=$'\033[0;33m'
RED=$'\033[0;31m'
BOLD=$'\033[1m'
RESET=$'\033[0m'

info()  { printf '%s==>%s %s\n' "$GREEN" "$RESET" "$*"; }
warn()  { printf '%s!!!%s %s\n' "$YELLOW" "$RESET" "$*" >&2; }
fatal() { printf '%sxxx%s %s\n' "$RED" "$RESET" "$*" >&2; exit 1; }

need() {
    command -v "$1" >/dev/null 2>&1 || fatal "missing required tool: $1"
}

random_hex() {
    # Portable across macOS/Linux: use openssl if available, else /dev/urandom.
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$1"
    else
        head -c "$(( $1 * 2 ))" /dev/urandom | od -An -vtx1 | tr -d ' \n'
    fi
}

prompt() {
    local varname=$1 message=$2 default=${3:-}
    local answer
    if [[ -n $default ]]; then
        printf '%s [%s]: ' "$message" "$default"
    else
        printf '%s: ' "$message"
    fi
    IFS= read -r answer </dev/tty || fatal "unable to read from tty"
    if [[ -z $answer ]]; then
        printf -v "$varname" '%s' "$default"
    else
        printf -v "$varname" '%s' "$answer"
    fi
}

prompt_yes_no() {
    local varname=$1 message=$2 default=${3:-n}
    local answer
    printf '%s [%s/%s]: ' \
        "$message" \
        "$([[ $default = y ]] && echo Y || echo y)" \
        "$([[ $default = y ]] && echo n || echo N)"
    IFS= read -r answer </dev/tty || fatal "unable to read from tty"
    answer=${answer:-$default}
    case "$answer" in
        y|Y|yes|YES) printf -v "$varname" '%s' "yes" ;;
        *)           printf -v "$varname" '%s' "no"  ;;
    esac
}

info "server-monitor-rs panel installer"

# --- 1. Preflight ------------------------------------------------------------
need docker
if ! docker compose version >/dev/null 2>&1; then
    fatal "'docker compose' not found. Install Docker Compose v2 (https://docs.docker.com/compose/install/)"
fi
if [[ ! -f $COMPOSE_SRC ]]; then
    fatal "expected compose file at $COMPOSE_SRC (run this script from the repo)"
fi

# --- 2. Choose install dir ---------------------------------------------------
prompt TARGET_DIR "Install directory" "$PWD/server-monitor-rs"
mkdir -p "$TARGET_DIR"
cd "$TARGET_DIR"

# --- 3. Collect config -------------------------------------------------------
prompt_yes_no USE_CADDY "Enable Caddy for automatic HTTPS + reverse proxy?" y

DOMAIN=""
if [[ $USE_CADDY = yes ]]; then
    prompt DOMAIN "Public domain name (e.g. panel.example.com)"
    [[ -z $DOMAIN ]] && fatal "domain cannot be empty when Caddy is enabled"
fi

prompt POSTGRES_USER "Postgres username" "monitor"
prompt POSTGRES_DB   "Postgres database" "monitor"
prompt_yes_no GEN_DB_PASSWORD "Generate a random Postgres password?" y
if [[ $GEN_DB_PASSWORD = yes ]]; then
    POSTGRES_PASSWORD=$(random_hex 24)
    info "generated Postgres password"
else
    prompt POSTGRES_PASSWORD "Postgres password" ""
    [[ -z $POSTGRES_PASSWORD ]] && fatal "password cannot be empty"
fi

JWT_SECRET=$(random_hex 32)
info "generated JWT secret (32 bytes)"

# HTTP bind: loopback when Caddy is in front, otherwise 0.0.0.0 so the panel
# is directly reachable on :8080.
if [[ $USE_CADDY = yes ]]; then
    PANEL_HTTP_BIND="127.0.0.1"
else
    PANEL_HTTP_BIND="0.0.0.0"
fi

# --- 4. Write files ----------------------------------------------------------
info "writing docker-compose.yml"
cp "$COMPOSE_SRC" "$TARGET_DIR/docker-compose.yml"

info "writing .env"
cat > "$TARGET_DIR/.env" <<EOF
# Generated by deploy/install-panel.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

PANEL_IMAGE=ghcr.io/lunyxiaoluny/server-monitor-panel:latest

JWT_SECRET=${JWT_SECRET}

LOG_FILTER=info,sqlx=warn
LOG_FORMAT=text

GITHUB_REPO=lunyxiaoluny/server-monitor-rs
GITHUB_TOKEN=

PANEL_HTTP_BIND=${PANEL_HTTP_BIND}
PANEL_GRPC_BIND=0.0.0.0
DOMAIN=${DOMAIN}
EOF
chmod 600 "$TARGET_DIR/.env"

if [[ $USE_CADDY = yes ]]; then
    info "writing Caddyfile for $DOMAIN"
    sed "s/{{DOMAIN}}/${DOMAIN//\//\\/}/g" "$CADDY_TEMPLATE" > "$TARGET_DIR/Caddyfile"
fi

# --- 5. Bring up the stack ---------------------------------------------------
info "starting containers"
if [[ $USE_CADDY = yes ]]; then
    docker compose --profile caddy up -d
else
    docker compose up -d
fi

# --- 6. Tell the user what to do next ----------------------------------------
cat <<POST

${BOLD}✅ Panel is up.${RESET}

Admin panel URL:
  $(if [[ $USE_CADDY = yes ]]; then echo "  https://${DOMAIN}"; else echo "  http://$(hostname -f 2>/dev/null || hostname):8080"; fi)

${BOLD}Next steps${RESET}
  1. Open the panel URL and create the admin account (task M3 will wire this up).
  2. In Settings → Agent connection, set the URL agents should dial:
       $(if [[ $USE_CADDY = yes ]]; then echo "  https://${DOMAIN}/grpc"; else echo "  http://<panel-host>:9090"; fi)
  3. Click "Add server" to get an install-agent command; run it on each monitored host.

Configuration saved to:
  - $TARGET_DIR/docker-compose.yml
  - $TARGET_DIR/.env          (secrets; keep this private)
$(if [[ $USE_CADDY = yes ]]; then echo "  - $TARGET_DIR/Caddyfile"; fi)

View logs:    cd $TARGET_DIR && docker compose logs -f
Stop panel:   cd $TARGET_DIR && docker compose down
POST
